-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-04-03 19:57:48 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP TABLE P_Department CASCADE CONSTRAINTS;
DROP TABLE P_Employee_Projects CASCADE CONSTRAINTS;
DROP TABLE P_Parent_child CASCADE CONSTRAINTS;
DROP TABLE P_Person CASCADE CONSTRAINTS;
DROP TABLE P_Projects CASCADE CONSTRAINTS;


CREATE TABLE P_Department
  (
    dept_no   INTEGER NOT NULL ,
    dept_name VARCHAR2 (255 CHAR) NOT NULL
  ) ;
ALTER TABLE P_Department ADD CONSTRAINT P_Department_PK PRIMARY KEY ( dept_no ) ;


CREATE TABLE P_Employee_Projects
  (
    employee_project_id   INTEGER NOT NULL ,
    P_Person_person_id    INTEGER ,
    P_Projects_project_no INTEGER
  ) ;
ALTER TABLE P_Employee_Projects ADD CONSTRAINT P_Employee_Projects_PK PRIMARY KEY ( employee_project_id ) ;


CREATE TABLE P_Parent_child
  (
    parent_child_id    INTEGER NOT NULL ,
    P_Person_person_id INTEGER,
     P_Person_person_id1 INTEGER
  ) ;
ALTER TABLE P_Parent_child ADD CONSTRAINT P_Parent_child_PK PRIMARY KEY ( parent_child_id ) ;


CREATE TABLE P_Person
  (
    person_id                      INTEGER NOT NULL ,
    first_name                     VARCHAR2 (255 CHAR) NOT NULL ,
    last_name                      VARCHAR2 (255 CHAR) NOT NULL ,
    home_address                   VARCHAR2 (255 CHAR) ,
    zipcode                        INTEGER ,
    home_phone                     INTEGER ,
    us_citizen                     CHAR (1) ,
    isFired                        CHAR (1) ,
    salary                         INTEGER ,
    employee_id                    INTEGER ,
    salary_exception               CHAR (1) ,
    bonus                          INTEGER ,
    P_Person_person_id             INTEGER ,
    type                           VARCHAR2 (255 CHAR) ,
    P_Parent_child_parent_child_id INTEGER ,
    P_Person_person_id1            INTEGER ,
    P_Department_dept_no           INTEGER
  ) ;
CREATE UNIQUE INDEX P_Person__IDX ON P_Person
  (
    P_Person_person_id ASC
  )
  ;
ALTER TABLE P_Person ADD CONSTRAINT P_Person_PK PRIMARY KEY ( person_id ) ;


CREATE TABLE P_Projects
  (
    project_no            INTEGER NOT NULL ,
    project_title         VARCHAR2 (255 CHAR) ,
    project_active        CHAR (1) ,
    end_date_month        INTEGER ,
    end_date_year         INTEGER ,
    est_person_hours      INTEGER ,
    P_Department_dept_no  INTEGER ,
    P_Person_person_id    INTEGER ,
    P_Projects_project_no INTEGER
  ) ;
ALTER TABLE P_Projects ADD CONSTRAINT P_Projects_PK PRIMARY KEY ( project_no ) ;


ALTER TABLE P_Employee_Projects ADD CONSTRAINT P_Emp_Proj_Person_FK FOREIGN KEY ( P_Person_person_id ) REFERENCES P_Person ( person_id ) ;

ALTER TABLE P_Employee_Projects ADD CONSTRAINT P_Emp_Proj_Proj_FK FOREIGN KEY ( P_Projects_project_no ) REFERENCES P_Projects ( project_no ) ;

ALTER TABLE P_Parent_child ADD CONSTRAINT P_Parent_child_P_Person_FK FOREIGN KEY ( P_Person_person_id ) REFERENCES P_Person ( person_id ) ;
ALTER TABLE P_Parent_child ADD CONSTRAINT P_Parent_child_P_Person_FKv1 FOREIGN KEY ( P_Person_person_id1 ) REFERENCES P_Person ( person_id ) ;

ALTER TABLE P_Person ADD CONSTRAINT P_Person_P_Department_FK FOREIGN KEY ( P_Department_dept_no ) REFERENCES P_Department ( dept_no ) ;

ALTER TABLE P_Person ADD CONSTRAINT P_Person_P_Parent_child_FK FOREIGN KEY ( P_Parent_child_parent_child_id ) REFERENCES P_Parent_child ( parent_child_id ) ;

ALTER TABLE P_Person ADD CONSTRAINT P_Person_P_Person_FK FOREIGN KEY ( P_Person_person_id ) REFERENCES P_Person ( person_id ) ;

ALTER TABLE P_Person ADD CONSTRAINT P_Person_P_Person_FKv1 FOREIGN KEY ( P_Person_person_id1 ) REFERENCES P_Person ( person_id ) ;

ALTER TABLE P_Projects ADD CONSTRAINT P_Projects_P_Department_FK FOREIGN KEY ( P_Department_dept_no ) REFERENCES P_Department ( dept_no ) ;

ALTER TABLE P_Projects ADD CONSTRAINT P_Projects_P_Person_FK FOREIGN KEY ( P_Person_person_id ) REFERENCES P_Person ( person_id ) ;

ALTER TABLE P_Projects ADD CONSTRAINT P_Projects_P_Projects_FK FOREIGN KEY ( P_Projects_project_no ) REFERENCES P_Projects ( project_no ) ;


-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             5
-- CREATE INDEX                             1
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   2
-- WARNINGS                                 0
